#!/usr/bin/env node
"use strict";

(function (path, self) {
  process.chdir(path.dirname(path.dirname(self)));
})(require('path'), process.argv[1]);

var ReBot = {
    'version': 'v0.0.1-alpha',
    'copyright': function () {
      console.log([
          ''
        , '  Copyright (C) 2013-2014 Jay Chan and Snakevil Zen.'
        , '  --LICENSE HERE--'
        , ''
        , '  Written and Maintained by Jay Chan and Snakevil Zen.'
        , '  Report bugs to <https://github.com/26480/wechat_rebot/issues/new>.'
      ].join('\n'));
    }
  }
  , program = require('commander');

console.log('\n  ReBot ' + ReBot.version + ' (Node.js ' + process.version + ')');

(function (options) {
  process.argv = [
      process.argv[0]
    , 'share/main'
    , options.worker
    , options.port
    , options.dir
  ];
  if (!options.back && !options.daemon) process.argv[process.argv.length] = 'tty';
  console.log('');
  require('../share/main');
})(
  program
    .version(ReBot.version)
    .option('-b, --back', 'run in background')
    .option('    --daemon')
    .option('-d, --dir <DIR>', 'customize database DIRectory, default: var/db', 'var/db')
    .option('-p, --port <PORT>', 'PORT to listen on, default: 80', parseInt, 80)
    .option('-w, --worker <WORKER>', 'customize WORKER', 'share/worker.js')
    .on('--help', ReBot.copyright)
    .removeAllListeners('version')
    .on('version', ReBot.copyright)
    .parse(process.argv)
);
